sudo: required
services:
  - docker

before_install:
  - docker build -t mexdocker/docker-react -f Dockerfile.dev .

script:
  - docker run mexdocker/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-2-375469996249"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"